### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by phihag** [laktak/atom-scrolly#5]
While running scrolly, I get mean warnings about it using outdated calls:

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/local/share/atom/resources/app/src/atom.js:54:11)
atom-workspace.<anonymous> (/home/phihag/.atom/packages/scrolly/lib/scrolly.js:18:22)
```

**Comment by phihag** [comment]
This is with atom 0.178.0-9105348.

**Comment by laktak** [comment]
I'm not really using Atom at the moment. Do you want to/know someone who wants to take over the package?

**Comment by kankaristo** [comment]
There's another Atom package with identical functionality: https://atom.io/packages/ctrl-dir-scroll

Although, I prefer the name on this package. :)

**Comment by laktak** [comment]
> Although, I prefer the name on this package. :)

I hope you can live with ctrl-dri-scroll ;) I had to unpublish since I'm not using Atom anymore and nobody wanted the package.
